# Site Settings
encoding                 : utf-8
url                      : "https://liuning0820.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : /liuning0820.github.io # the subpath of your site, e.g. "/blog"
email                    : liuning0820@outlook.com
theme                    : jekyll-theme-slate
search                   : true # true, false (default), enables basic site search powered by Lunr

gems:
  - jekyll-feed
