# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
encoding                 : utf-8
url                      : "https://liuning0820.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
email                    : liuning0820@outlook.com
theme                    : jekyll-theme-slate
search                   : true # true, false (default), enables basic site search powered by Lunr

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - Dockerfile.mdspell
  - Jenkinsfile

# #摘要显示分割线
excerpt_separator: <! --more-- >

# Pagination Settings

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

theme: jekyll-theme-slate


# Comment 这是disqus的评论系统
comment:
    disqus: liuning0820


# Collections
# https://jekyllrb.com/docs/collections/

# collections:
#     - staff_members
    
collections:
  staff_members:
    output: true
    permalink: /:collection/:path/

  