name: Jekyll site CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "jekyll build --future && gem install html-proofer && gem which html-proofer && pwd && ls && /usr/gem/gems/html-proofer-3.11.1/bin/htmlproofer ./_site --disable-external 'true' --log-level debug"
